### ISSUE TITLE
adding rules in web inteface

### ISSUE THREAD

**Issue by masoudqashqai** [zecure/shadowd_rules#2]
hi, documents in shadowd.zecure.org stated that "The rules can be imported via the web interface", but i cant figure out where can i add rules!

**Comment by zit-hb** [comment]
Hey. There is an import button at the bottom of the blacklist, whitelist, and integrity pages: https://shadowd.zecure.org/img/tutorials/blacklist.png

**Comment by dattmckdj** [comment]
Hi zit-hb,
When importing the ignored rule files to the sites, I receive a 500 internal server error. Are the ignored rules supposed to be imported via the web interface?

**Comment by zit-hb** [comment]
Hi @dattmse140171 ,

No, the ignore file has to be specified through the config of the connector. It makes sure that the connector never sends this user input to the shadowd server.
