### ISSUE TITLE
Request on some example rules to test on DVWA

### ISSUE THREAD

**Issue by dattmckdj** [zecure/shadowd_rules#3]
Hi All,

I am having trouble learning the rule format to block attack requests such as SQLi, XSS, Brute Force, and Command Injection, with DVWA as the target.
I tried some rules available on this repository and write some of my own but no luck so far.
I am hoping you can help me with this problem.

Best regards,
DatTM

**Comment by zit-hb** [comment]
Hi DatTM,

I am not sure I understand the question. Are you trying to detect those attacks with the blacklist only? If yes, make sure that the blacklist threshold for the profile is low enough (for example, `2`). This should block almost any SQL injection, XSS, or command injection. Shadow Daemon does not protect against brute force. It is not necessary to create any rules for DVWA.

None of the rules in this repository are for DVWA anyway.

**Comment by dattmckdj** [comment]
Hi zit-hb,

I will try to lower the profile threshold and update you on the issue.
